### ISSUE TITLE
Provide better examples

### ISSUE THREAD

**Issue by scls19fr** [JuliaComputing/AMQPClient.jl#15]
Hello,

It will be nice if we could find examples comparables to 
https://www.rabbitmq.com/tutorials/tutorial-one-python.html

1. Hello World
2. Work queues
3. Publish/Subscribe
4. Routing
5. Topics
6. RPC

(code available for several language at https://github.com/rabbitmq/rabbitmq-tutorials )

I'm personally trying to use Python `receive.py` script (from "Hello World" example) and write a Julia `send.jl` script ie I'm trying to convert

```python
#!/usr/bin/env python
import pika

connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
channel = connection.channel()


channel.queue_declare(queue='hello')

channel.basic_publish(exchange='',
                      routing_key='hello',
                      body='Hello World!')
print(" [x] Sent 'Hello World!'")
connection.close()
```

to Julia

I did this:

```julia
using AMQPClient

port = AMQPClient.AMQP_DEFAULT_PORT

# login = ""  # "guest"
# password = ""  # "guest"
# auth_params = Dict("MECHANISM"=>"AMQPLAIN", "LOGIN"=>login, "PASSWORD"=>password)
auth_params = Dict("MECHANISM"=>"AMQPLAIN")

conn = connection(;virtualhost="/", host="localhost", port=port, auth_params=auth_params)

chan = channel(conn, AMQPClient.UNUSED_CHANNEL, true)

success, message_count, consumer_count = queue_declare(chan, "hello")

basic_publish(chan, "Hello World!"; exchange=EXCG_DIRECT, routing_key="hello")
println(" [x] Sent 'Hello World!'")

if isopen(conn)
    close(conn)
    # close is an asynchronous operation. To wait for the negotiation to complete:
    AMQPClient.wait_for_state(conn, AMQPClient.CONN_STATE_CLOSED)
end
```

but Julia script is blocked at:

```julia
conn = connection(;virtualhost="/", host="localhost", port=port, auth_params=auth_params)
```

Any idea what is going wrong? 

Kind regards

**Comment by jasonmarquette** [comment]
One thing to check is if your port that you are using isn’t being blocked by a firewall.

**Comment by scls19fr** [comment]
I don't think it's a firewall issue because a similar Python script works fine.

**Comment by scls19fr** [comment]
Examples are now available at https://github.com/rabbitmq/rabbitmq-tutorials/blob/main/julia/README.md thanks to @kracekumar 
Maybe it should be mentioned in the documentation of this library.
