### ISSUE TITLE
Logging reports crash of debug message

### ISSUE THREAD

**Issue by casabre** [JuliaComputing/AMQPClient.jl#38]
Running the AMQP client in a Docker environment throws the following error continuously for multiple times in AMQPClient. The client itself is operational but dumps a lot of error messages to the log which are making debugging of the own code for "`Service`" quite hard.

```bash
Exception handling log message: MethodError(Service.var"#3#5"{String}("yyyy-mm-dd HH:MM:SS"), ((level = Debug, message = "Frame Conversion: generic => method", _module = AMQPClient, group = :types, id = :AMQPClient_96aa8459, file = "/root/.julia/packages/AMQPClient/P6CBt/src/types.jl", line = 242, kwargs = Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}()),), 0x0000000000006d21)
module=AMQPClient  file=/root/.julia/packages/AMQPClient/P6CBt/src/types.jl  line=242
Second exception: MethodError(Service.var"#3#5"{String}("yyyy-mm-dd HH:MM:SS"), ((level = Error, message = "Exception while generating log record in module AMQPClient at /root/.julia/packages/AMQPClient/P6CBt/src/types.jl:242", _module = AMQPClient, group = :logevent_error, id = :AMQPClient_96aa8459, file = "/root/.julia/packages/AMQPClient/P6CBt/src/types.jl", line = 242, kwargs = Base.Iterators.Pairs{Symbol,Tuple{MethodError,Array{Union{Ptr{Nothing}, Base.InterpreterIP},1}},Tuple{Symbol},NamedTuple{(:exception,),Tuple{Tuple{MethodError,Array{Union{Ptr{Nothing}, Base.InterpreterIP},1}}}}}(:exception => (MethodError(AcquisitionService.var"#3#5"{String}("yyyy-mm-dd HH:MM:SS"), ((level = Debug, message = "Frame Conversion: generic => method", _module = AMQPClient, group = :types, id = :AMQPClient_96aa8459, file = "/root/.julia/packages/AMQPClient/P6CBt/src/types.jl", line = 242, kwargs = Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}()),), 0x0000000000006d21), [Ptr{Nothing} @0x00007fcf9dde5aec, Ptr{Nothing} @0x00007fcf9dded454, Ptr{Nothing} @0x00007fcf9ddef1bc, Ptr{Nothing} @0x00007fcf70c13d46, Ptr{Nothing} @0x00007fcf70c13bfb, Ptr{Nothing} @0x00007fcf70c13c7e, Ptr{Nothing} @0x00007fcf9ddeee27, Ptr{Nothing} @0x00007fcf70bf14ae, Ptr{Nothing} @0x00007fcf70bf17ad, Ptr{Nothing} @0x00007fcf70bf4192, Ptr{Nothing} @0x00007fcf70bf4dda, Ptr{Nothing} @0x00007fcf70bf4e0c, Ptr{Nothing} @0x00007fcf9ddeee27, Ptr{Nothing} @0x00007fcf9de0d96e, Ptr{Nothing} @0x0000000000000000]))),), 0x0000000000006d21)
```

The following lines are affected for instance
- 242 in types.jl
- 159 in types.jl
- 164 in types.jl
- 282 in protocol.jl
- 426 in protocol.jl
...

**Comment by tanmaykm** [comment]
This error seems unrelated to the AMQPClient library. I tested AMQPClient in debug mode and it does log the message properly:

```
┌ Debug: reading method payload
│   class = 0x0014
│   method = 0x000b
│   nargs = 1
└ @ AMQPClient ~/.julia/dev/AMQPClient/src/types.jl:159
...
┌ Debug: Frame Conversion: generic => method
└ @ AMQPClient ~/.julia/dev/AMQPClient/src/types.jl:242
...
```

The errors report a `MethodError` in some code that refers to the entity named `Service` that you mentioned. So maybe there is something there that needs to be examined?

**Comment by casabre** [comment]
@tanmaykm I do not agree with your findings because the Julia log is especially referring to specific line in the e.g. types.jl. Maybe that my call is introducing a wrong interpretation of the variables &rarr; could be that they are resulting to `nothing` in your specific @debug call and thus, the log crashes. But frankly spoken, I am just sending JSON data converted to string and finally to a `AMQPClient.Message`.

But I am wondering how the string data can introduce such errors. Here is a snippet of my publishing code.
```julia
data = json(Dict(some JSON data));

data = Vector{UInt8}(data);
msg = Message(data, content_type = "application/json", delivery_mode = PERSISTENT);
basic_publish(channel, msg; exchange = exchange, routing_key = route);
```
where channel, exchange and route are set to my specific setup.

**Comment by tanmaykm** [comment]
Yes, just sending string/byte data like you mentioned should be fine, that's what all messages are after all.

The occurrence of this: `MethodError(Service.var"#3#5"{String}("yyyy-mm-dd HH:MM:SS")` in the log snippet you had provided is a bit strange though. Is it possible that you are using a different logger?

**Comment by casabre** [comment]
Let's say, I am not overriding it by purpose. I am using AMQPClient in parallel with [Genie.jl](https://github.com/GenieFramework/Genie.jl). After digging a bit in the code, the web framework is overriding the default logger &rarr; https://github.com/GenieFramework/Genie.jl/blob/master/files/new_app/config/initializers/logging.jl. But it seems to me not that critical because it is adapting just the message content.

But strange enough, some AMQPClient debug message are printed correctly, some are throwing these errors.

**Comment by tanmaykm** [comment]
Yes, strange indeed. The log statement at line 242 of types.jl, for example, is just a simple string. https://github.com/JuliaComputing/AMQPClient.jl/blob/9fed71e2289034c3dca82e2337e3863332ce69d4/src/types.jl#L242
There does not seem to be else here that can cause this error.

I do not understand Genie.jl internals. Maybe best to raise an issue at Genie.jl and see if something turns up?

**Comment by casabre** [comment]
> Maybe best to raise an issue at Genie.jl and see if something turns up?

Yes, that sounds reasonable. Because I am also not into deep the Genie.jl internals. I would come back to this thread if something is still related to AMQP.

Thanks anyway for your support!
