### ISSUE TITLE
connection(...) returns Channel

### ISSUE THREAD

**Issue by mfalt** [JuliaComputing/AMQPClient.jl#51]
I am not sure how this is not caught in the tests but the`connection` function returns a `MessageChannel`, not a `Connection` (contrary to the docs).
Its an easy fix if you want me to create a PR.
https://github.com/JuliaComputing/AMQPClient.jl/blob/f596fe4102539cef7c59d7184a230d49022247aa/src/protocol.jl#L582-L676

**Comment by tanmaykm** [comment]
fixed by #52
